### ISSUE TITLE
Make tx gas costs inclusion optional with new accounting setting

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#175]
## Problem Definition

History processing and tax report calculation at the moment always takes into account gas costs for all your ethereum transaction movements as "loss".

This should be made customizable.

## Tasks
![todo](https://user-images.githubusercontent.com/1658405/46442232-30432380-c769-11e8-95af-209620519083.png)

Add a new accounting option named `account_for_gas_costs`. 

- [ ] The location of the setting in the UI should be as shown in the screenshot above.
- [ ] The UI part should be done just like `include_crypto2crypto` is done. Source link [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/ui/accounting_settings.js#L94). Note: There is more places in the front-end code where it should be added.
- [ ] Pass the option to the backend and specifically to the accountant class as seen [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L88) and as is also done for `include_crypto2crypto`.
- [ ] Use the option in the `account_for_gas_costs()` function [here](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/accounting/accountant.py#L178).

**Comment by nhultz** [comment]
I'd like to pick this one up.

One question I had from the issue description, are you just looking to make it so either the reporting will include gas costs as a loss or just not include them at all?

**Comment by LefterisJP** [comment]
> are you just looking to make it so either the reporting will include gas costs as a loss or just not include them at all

yep. 

Sure you can pick it up!

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotkehlchenio/rotkehlchen/pull/193
