### ISSUE TITLE
Write OTC Trade UI Tests

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#292]
## Problem Definition

We need UI tests for adding, removing and editing an external trade.

## Task

- [ ] Write a test that adds two external trade via the OTC Trades pane and sees them in the OTC Trades table
- [ ] Then write a test that edits one trade and sees the change in the table
- [ ] Finally write a test that removes one trade and sees it removed from the table.
