### ISSUE TITLE
Detect newer versions and prompt users for upgrading

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#453]
## Abstract

Unless users follow our social media announcements they don't get to know when a new version is released. It would be nice to have a warning for them that a new version is released.

## Task

- [ ] Write a check that uses the github API to find the latest release and compares it to the one the user is running. This check should run either only at the start or periodically.

- [ ] If the check succeeds then the user should be prompted to click on the link to download and upgrade to the new release after checking the changelog

- [ ] Add a test for this as usual
